name: HiddenPlayersInTab
version: ${project.version}
main: me.jaimemartz.hpit.Main
depend: [ProtocolLib]
commands:
  testhide:
    description: This is a test
    permission: hiddenplayersintab.testhide